
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::280362093954:role/default-eks-node-group-20260321102024234600000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::280362093954:user/terraform-user
      username: terraform-user
      groups:
        - system:masters

    - userarn: arn:aws:iam::280362093954:user/dev-project
      username: jenkins
      groups:
        - system:masters
