apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: devops-app-secret
      property: DB_USER

  - secretKey: DB_PASS
    remoteRef:
      key: devops-app-secret
      property: DB_PASS

  - secretKey: DB_HOST
    remoteRef:
      key: devops-app-secret
      property: DB_HOST
